site_name: Smikkelen Schranzen Slurpen
site_description: Smikkelen Schranzen Slurpen

theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - Italian:
    - tomato sauce: recipes/tomatosauce.md
  - Vlaamsch:
    - frikandon: recipes/frikandon.md

markdown_extensions:
  - footnotes
